<?php 
    require_once("index.html"); 
    require_once("/");
    require_once("css/");
    require_once("js/");
    require_once("images/");
    require_once("pages/");
    require_once("admin/");
    require_once("admin/index.php");
?>